
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmad Dimas AM
 */
public class pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN SMK TELKOM MALANG");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 580, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 790, 110);

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setLayout(null);

        tblData.setBackground(new java.awt.Color(255, 255, 102));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 750, 300);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(340, 20, 110, 40);

        jButton2.setBackground(new java.awt.Color(51, 255, 102));
        jButton2.setText("SELESAI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(10, 20, 110, 40);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("PEMINJAMAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(170, 20, 110, 40);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(510, 20, 120, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 130, 770, 380);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 520);

        setSize(new java.awt.Dimension(804, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String id = tblData.getValueAt(baris, 0).toString();
                        
            Date now = new Date();
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat_k = null;
            Date day = null;
            try {
                dateFormat_k = date.parse(tblData.getValueAt(baris, 7).toString());
            } catch (ParseException ex) {
                Logger.getLogger(pinjam.class.getName()).log(Level.SEVERE, null, ex);
            }
            int kembali = dateFormat_k.getDate();
            int sekarang = now.getDate();
            int denda = 0;
            
            int terlambat = sekarang - kembali;
            
            if(terlambat > 0){
                denda = 10000 * terlambat;
                alert.showMessageDialog(this, "Anda didenda = "+denda, "Warning", alert.WARNING_MESSAGE);
            }
            
            String sql = "UPDATE tb_pinjam SET status='selesai', denda='"+denda+"' WHERE id='"+id+"'";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Buku sudah dikembalikan", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Gagal mengembalikan buku", "GAGAL", alert.WARNING_MESSAGE);
            }
        } else {
            alert.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu!", "Error", alert.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new pinjam().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MessageFormat header = new MessageFormat("Peminjaman Buku SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}      ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (PrinterException ex) {
            System.err.format("Cannot print %s%n", ex.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void selectData() {
        String kolom[] = {"ID", "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status", "Denda"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String sql = "SELECT * FROM tb_pinjam";
        ResultSet rs = KoneksiDB.executeQuery(sql);
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String no = rs.getString(2);
                String nama = rs.getString(3);
                String alamat = rs.getString(4);
                String jb = rs.getString(5);
                String judul = rs.getString(6);
                String tgl_pinjam = rs.getString(7);
                String tgl_kembali = rs.getString(8);
                String status = rs.getString(9);
                String denda = rs.getString(10);
                String data[] = {id, no, nama, alamat, jb, judul, tgl_pinjam, tgl_kembali, status, denda};
                dtm.addRow(data);
            }
        } catch (SQLException e){
            Logger.getLogger(pengembalian.class.getName()).log(Level.SEVERE, null, e);
        }
        tblData.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
