/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmad Dimas AM
 */

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

public class pinjam extends javax.swing.JFrame {

    /**
     * Creates new form pinjam
     */
    public pinjam() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert = new javax.swing.JOptionPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtNO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        jenisBuku = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PINJAM BUKU SMK TELKOM MALANG");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 580, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 910, 80);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 28, 250, 2);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setText("ISIAN DATA PEMINJAM");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 0, 190, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel4.setText("Tgl Pinjam");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 450, 70, 20);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel5.setText("Jenis Buku");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 300, 170, 20);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel6.setText("Judul Buku");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 370, 100, 20);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 170, 150, 20);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel9.setText("NO ANGGOTA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 30, 170, 20);
        jPanel3.add(txtNama);
        txtNama.setBounds(10, 120, 220, 30);
        jPanel3.add(txtJudul);
        txtJudul.setBounds(10, 400, 220, 30);
        jPanel3.add(txtNO);
        txtNO.setBounds(10, 50, 220, 30);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel8.setText("NAMA");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 100, 140, 20);
        jPanel3.add(tgl_pinjam);
        tgl_pinjam.setBounds(90, 450, 140, 30);

        jenisBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Komik", "Pendidikan", "Majalah" }));
        jPanel3.add(jenisBuku);
        jenisBuku.setBounds(10, 330, 220, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 190, 220, 96);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel13.setText("Tgl Kembali");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 500, 70, 20);
        jPanel3.add(tgl_kembali);
        tgl_kembali.setBounds(90, 500, 140, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 250, 540);

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(220, 10, 80, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(20, 10, 80, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(120, 10, 80, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(520, 10, 80, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(320, 10, 80, 30);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(420, 10, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 90, 640, 50);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setLayout(null);

        tblData.setBackground(new java.awt.Color(255, 255, 204));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Tanggal Lahir", "Jenis Kelamin", "Kelas", "Email", "Asal SMP", "Alamat", "No Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 620, 420);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(270, 150, 640, 470);

        setSize(new java.awt.Dimension(925, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtNO.setText("");
        txtNama.setText("");
        tgl_pinjam.setDate(null);
        tgl_kembali.setDate(null);
        txtJudul.setText("");
        txtAlamat.setText("");
        jenisBuku.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String jb = jenisBuku.getSelectedItem().toString();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal_p = dateFormat.format(tgl_pinjam.getDate());
        String tanggal_k = dateFormat.format(tgl_kembali.getDate());

        if(txtNO.getText().equals("") || txtNama.getText().equals("") || tanggal_p.equals("") || jb.equals("") ||
            txtJudul.getText().equals("") || tanggal_k.equals("") ||
            txtAlamat.getText().equals("")){
            
            alert.showMessageDialog(this, "Harap Lengkapi Data", "Error", alert.WARNING_MESSAGE);
        } else {
            String sql = "INSERT INTO tb_pinjam VALUES ("+null+", '"+txtNO.getText()+"', '"+txtNama.getText()+"'"
                    + ", '"+txtAlamat.getText()+"', '"+jb+"', '"+txtJudul.getText()+"', '"+tanggal_p+"'"
                    + ", '"+tanggal_k+"', 'pinjam', '"+0+"')";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Data Gagal Ditambahkan", "GAGAL", alert.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String id = tblData.getValueAt(baris, 0).toString();
            String sql = "DELETE FROM tb_pinjam WHERE id='"+id+"'";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Data Berhasil Dihapus", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Data Gagal Dihapus", "GAGAL", alert.WARNING_MESSAGE);
            }
        } else {
            alert.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu!", "Error", alert.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            txtNO.setText(tblData.getValueAt(baris, 1).toString());
            txtNama.setText((String) tblData.getValueAt(baris, 2));
            txtAlamat.setText(tblData.getValueAt(baris, 3).toString());
            jenisBuku.setSelectedItem(tblData.getValueAt(baris, 4).toString());
            txtJudul.setText(tblData.getValueAt(baris, 5).toString());
            
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
            Date dateFormat_p = null;
            Date dateFormat_k = null;
            try {
                dateFormat_p = date.parse(tblData.getValueAt(baris, 6).toString());
                dateFormat_k = date.parse(tblData.getValueAt(baris, 6).toString());
            } catch (ParseException ex) {
                Logger.getLogger(pinjam.class.getName()).log(Level.SEVERE, null, ex);
            }
            tgl_pinjam.setDate(dateFormat_p);
            tgl_kembali.setDate(dateFormat_k);
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        selectData();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MessageFormat header = new MessageFormat("Peminjaman Buku SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}      ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (PrinterException ex) {
            System.err.format("Cannot print %s%n", ex.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new pengembalian().show();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void selectData() {
        String kolom[] = {"ID", "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status", "Denda"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String sql = "SELECT * FROM tb_pinjam";
        ResultSet rs = KoneksiDB.executeQuery(sql);
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String no = rs.getString(2);
                String nama = rs.getString(3);
                String alamat = rs.getString(4);
                String jb = rs.getString(5);
                String judul = rs.getString(6);
                String tgl_pinjam = rs.getString(7);
                String tgl_kembali = rs.getString(8);
                String status = rs.getString(9);
                String denda = rs.getString(10);
                String data[] = {id, no, nama, alamat, jb, judul, tgl_pinjam, tgl_kembali, status, denda};
                dtm.addRow(data);
            }
        } catch (SQLException e){
            Logger.getLogger(pengembalian.class.getName()).log(Level.SEVERE, null, e);
        }
        tblData.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jenisBuku;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
